version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      support-dependencies:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
